# Generated by Django 5.2.5 on 2025-11-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion_notificacion',
            fields=[
                ('idconfiguracion_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_de_evento', models.CharField(max_length=45)),
                ('metodo', models.CharField(max_length=45)),
                ('activo', models.BooleanField(default=True)),
                ('minutos_antes_turno', models.IntegerField(default=30)),
                ('intentos_maximo', models.IntegerField(default=3)),
                ('intervalo_reintesto', models.IntegerField(default=10)),
            ],
            options={
                'db_table': 'configuracion_notificacion',
                'managed': True,
            },
        ),
    ]
