# Generated by Django 6.0.3 on 2026-04-03 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion_notificacion',
            fields=[
                ('idconfiguracion_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_de_evento', models.CharField(max_length=45)),
                ('metodo', models.CharField(max_length=45)),
                ('activo', models.BooleanField(default=True)),
                ('minutos_antes_turno', models.IntegerField(default=30)),
                ('intentos_maximo', models.IntegerField(default=3)),
                ('intervalo_reintesto', models.IntegerField(default=10)),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'configuracion_notificacion',
                'managed': True,
            },
        ),
    ]
