# Generated by Django 6.0.3 on 2026-04-11 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion_notificacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuracion_notificacion',
            old_name='usuario_id',
            new_name='usuario',
        ),
    ]
