# Generated by Django 6.0.3 on 2026-04-03 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidencia', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Escalamiento',
            fields=[
                ('idescalamiento', models.AutoField(primary_key=True, serialize=False)),
                ('nivel', models.IntegerField()),
                ('tipo_notificacion', models.CharField(max_length=45)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('confirmado', 'Confirmado'), ('fallido', 'Fallido')], default='enviado', max_length=45)),
                ('mensaje_enviado', models.TextField(blank=True, null=True)),
                ('fecha_escalamiento', models.DateTimeField(auto_now=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('incidencia_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidencia.incidencia')),
                ('usuario_notificado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'escalamiento',
                'managed': True,
            },
        ),
    ]
