# Generated by Django 5.2.5 on 2025-11-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escalamiento',
            fields=[
                ('idescalamiento', models.AutoField(primary_key=True, serialize=False)),
                ('nivel', models.IntegerField()),
                ('tipo_notificacion', models.CharField(max_length=45)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('confirmado', 'Confirmado'), ('fallido', 'Fallido')], max_length=45)),
                ('mensaje_enviado', models.TextField(blank=True, null=True)),
                ('fecha_escalamiento', models.DateTimeField(auto_now=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'escalamiento',
                'managed': True,
            },
        ),
    ]
