# Generated by Django 5.2.5 on 2025-10-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escalamiento',
            fields=[
                ('idescalamiento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_notificacion', models.CharField(max_length=45)),
                ('estado', models.CharField(max_length=45)),
                ('mensaje_enviado', models.CharField(max_length=45)),
                ('fecha_escalamiento', models.DateTimeField(auto_now=True)),
                ('fecha_respuesta', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'escalamiento',
                'managed': False,
            },
        ),
    ]
