# Generated by Django 5.2.5 on 2025-10-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template_notificacion',
            fields=[
                ('idtemplate_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('tipo_evento', models.CharField(max_length=45)),
                ('asunto_email', models.CharField(max_length=45)),
                ('cuerpo_email', models.CharField(max_length=500)),
                ('mensaje_sms', models.CharField(max_length=45)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'template_notificacion',
                'managed': False,
            },
        ),
    ]
