# Generated by Django 6.0.3 on 2026-04-03 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template_notificacion',
            fields=[
                ('idtemplate_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('tipo_evento', models.CharField(max_length=45)),
                ('asunto_email', models.CharField(max_length=150)),
                ('cuerpo_email', models.TextField()),
                ('mensaje_sms', models.TextField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'template_notificacion',
                'managed': True,
            },
        ),
    ]
