# Generated by Django 5.2.5 on 2025-11-12 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escalamiento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial_notificacion',
            fields=[
                ('idhistorial_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_notificacion', models.CharField(max_length=45)),
                ('contenido', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('enviado', 'Enviado'), ('entregado', 'Entregado'), ('leido', 'Leído'), ('fallido', 'Fallido')], max_length=45)),
                ('mensaje_error', models.TextField(blank=True, null=True)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('escalamiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='escalamiento.escalamiento')),
            ],
            options={
                'db_table': 'historial_notificacion',
                'managed': True,
            },
        ),
    ]
