# Generated by Django 5.2.5 on 2025-10-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Historial_notificacion',
            fields=[
                ('idhistorial_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_notificacion', models.CharField(max_length=45)),
                ('contenido', models.CharField(max_length=45)),
                ('estado', models.CharField(max_length=45)),
                ('error_msj_notificacion', models.CharField(max_length=45)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('fecha_lectura', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'historial_notificacion',
                'managed': False,
            },
        ),
    ]
