# Generated by Django 5.2.5 on 2025-11-12 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('historial_notificacion', '0001_initial'),
        ('relevo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial_notificacion',
            name='relevo_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='relevo.relevo'),
        ),
    ]
