# Generated by Django 6.0.3 on 2026-04-11 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rol',
            old_name='id_rol',
            new_name='idrol',
        ),
    ]
