# Generated by Django 6.0.3 on 2026-08-04 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0002_rename_id_rol_rol_idrol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='nombre',
            field=models.CharField(choices=[('guardia', 'Guardia'), ('lider', 'Líder'), ('encargado', 'Encargado'), ('relevo', 'Relevo')], default='guardia', max_length=50),
        ),
    ]
