# Generated by Django 5.2.5 on 2025-11-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo_escalamiento',
            fields=[
                ('idgrupo_escalamiento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('num_orden_escalamiento', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'grupo_escalamiento',
                'managed': True,
            },
        ),
    ]
