# Generated by Django 5.2.5 on 2025-10-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo_escalamiento',
            fields=[
                ('idgrupo_escalamiento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=250)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'grupo_escalamiento',
                'managed': False,
            },
        ),
    ]
