# Generated by Django 6.0.3 on 2026-08-04 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
    ]
