# Generated by Django 6.0.3 on 2026-08-16 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_usuario_fecha_ingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='hora_entrada',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='hora_salida',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='observaciones_jornada',
            field=models.TextField(blank=True, null=True),
        ),
    ]
