# Generated by Django 6.0.3 on 2026-04-03 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('turno', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('idincidencia', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('gravedad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], max_length=45)),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('en_proceso', 'En Proceso'), ('resuelta', 'Resuelta'), ('cerrada', 'Cerrada')], default='abierta', max_length=45)),
                ('fecha_ocurrencia', models.DateTimeField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacionn', models.DateTimeField(blank=True, null=True)),
                ('turno_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turno.turno')),
                ('usuario_reporta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidencias_reportadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'incidencia',
                'managed': True,
            },
        ),
    ]
