# Generated by Django 5.2.5 on 2025-10-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('idincidencia', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=250)),
                ('gravedad', models.CharField(max_length=45)),
                ('estado', models.CharField(max_length=45)),
                ('fecha_ocurrencia', models.DateTimeField(auto_now_add=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacionn', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'incidencia',
                'managed': False,
            },
        ),
    ]
