# Generated by Django 5.2.5 on 2025-11-12 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidencia', '0001_initial'),
        ('turno', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='turno_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turno.turno'),
        ),
    ]
