# Generated by Django 5.2.5 on 2025-11-12 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calendario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('idturno', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('activo', 'Activo'), ('completado', 'Completado'), ('perdido', 'Perdido')], max_length=45)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('calendario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendario.calendario')),
            ],
            options={
                'db_table': 'turno',
                'managed': True,
            },
        ),
    ]
