# Generated by Django 5.2.5 on 2025-10-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('idturno', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=250)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateTimeField(auto_now=True)),
                ('fecha_fin', models.DateTimeField(auto_now=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'turno',
                'managed': False,
            },
        ),
    ]
