# Generated by Django 6.0.3 on 2026-04-11 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turno', '0002_turno_grupo_escalamiento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turno',
            old_name='calendario_id',
            new_name='calendario',
        ),
    ]
