# Generated by Django 6.0.3 on 2026-04-03 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('turno', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Relevo',
            fields=[
                ('idrelevo', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.CharField(max_length=45)),
                ('estado', models.CharField(choices=[('solicitado', 'Solicitado'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado'), ('completado', 'Completado')], max_length=45)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('turno_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relevos_destino', to='turno.turno')),
                ('turno_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relevo_origen', to='turno.turno')),
                ('usuario_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_toma_turno', to=settings.AUTH_USER_MODEL)),
                ('usuario_origen_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_que_asigna', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'relevo',
                'managed': True,
            },
        ),
    ]
