# Generated by Django 5.2.5 on 2025-10-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Relevo',
            fields=[
                ('idrelevo', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.CharField(max_length=45)),
                ('estado', models.CharField(max_length=45)),
                ('notas', models.CharField(max_length=250)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(auto_now=True)),
                ('fecha_completado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'relevo',
                'managed': False,
            },
        ),
    ]
