# Generated by Django 5.2.5 on 2025-11-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Relevo',
            fields=[
                ('idrelevo', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.CharField(max_length=45)),
                ('estado', models.CharField(choices=[('solicitado', 'Solicitado'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado'), ('completado', 'Completado')], max_length=45)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'relevo',
                'managed': True,
            },
        ),
    ]
