# Generated by Django 5.2.5 on 2025-11-12 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('relevo', '0001_initial'),
        ('turno', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relevo',
            name='turno_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relevos_destino', to='turno.turno'),
        ),
        migrations.AddField(
            model_name='relevo',
            name='turno_origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relevo_origen', to='turno.turno'),
        ),
    ]
