# Generated by Django 5.2.5 on 2025-11-12 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('relevo', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='relevo',
            name='usuario_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_toma_turno', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='relevo',
            name='usuario_origen_solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_que_asigna', to=settings.AUTH_USER_MODEL),
        ),
    ]
