# Generated by Django 6.0.3 on 2026-04-03 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grupo_escalamiento', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario_grupo',
            fields=[
                ('idusuario_grupo', models.AutoField(primary_key=True, serialize=False)),
                ('prioridad', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('grupo_escalamiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='grupo_escalamiento.grupo_escalamiento')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usuario_grupo',
                'managed': True,
                'unique_together': {('usuario', 'grupo_escalamiento')},
            },
        ),
    ]
