# Generated by Django 5.2.5 on 2025-11-12 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grupo_escalamiento', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario_grupo',
            fields=[
                ('idusuario_grupo', models.AutoField(primary_key=True, serialize=False)),
                ('prioridad', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('grupo_escalamiento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupo_escalamiento.grupo_escalamiento')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usuario_grupo',
                'managed': True,
            },
        ),
    ]
