# Generated by Django 5.2.5 on 2025-10-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario_grupo',
            fields=[
                ('idusuario_grupo', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'usuario_grupo',
                'managed': False,
            },
        ),
    ]
